### ISSUE TITLE
Some settings reset to default upon server start

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Wesley1808/ServerCore-Fabric#3]
**Describe the bug**

These settings revert to its default values when the server starts:

> item_merge_radius = 0.5
xp_merge_radius = 0.5
max_view_distance = 10

Possibly some others, that I don't use.

**Reproduce**

1. Open servercore.toml and set the following settings to

> item_merge_radius = 5
xp_merge_radius = 5
max_view_distance = 50

Save & close.

2. Start the server, open the servercore.toml again and see that those settings got reset to its default values.

**Expected behavior**

Settings should not reset.

**Versions** -Latest is not a version!

ServerCore: servercore-1.2.1-1.17.1
Minecraft: 1.17.1

**Mod incompatibilities**

~

Logs: https://gist.github.com/Footage2-Amply-Pounce/9e051048c84e7e41e66a108d68b1e68b
My full settings: https://gist.github.com/Footage2-Amply-Pounce/ee243884dfb330e0798803e6f3849265
This is what it resets to: https://gist.github.com/Footage2-Amply-Pounce/a43673140ec9eda455ef4c0e42d14e28

**Comment by Wesley1808** [comment]
Some settings have constraints so users can't fill in entries in ways that might crash / corrupt things.
For example:
- item_merge_radius & xp_merge_radius is of type `Double`. Filling in an Integer will crash the server upon loading.
Solution would be to set 5 to 5.0.

The case of max_view_distance was set to a cap of 32, but since there might be mods out there that increase it I should probably remove that.

Note, you can also adjust all of these settings ingame by using /servercore. Almost all settings have affect without requiring a restart.

**Comment by Footage2-Amply-Pounce** [comment]
Ah, thank you. After setting the first 2 settings to 5.0 and max view distance to 32, it no longer resets. 32 is going to be enough for me personally at the moment, but I do indeed have mods that allow for higher values on clients, so would be nice to have a higher limit/no limit(?) in the future.

And thanks for reminding me about the command, I totally forgot 😄
